#!/usr/bin/env python3
"""
TRIDENT-DOC word lists — comprehensive concrete nouns and action verbs
for technical documentation claim-checking.
"""

CONCRETE_NOUNS = [
    # Technology & infrastructure
    "API", "SDK", "CLI", "URL", "URI", "DNS", "IP", "SSH", "HTTPS", "TLS", "SSL",
    "file", "database", "server", "key", "token", "port",
    "config", "env", "variable", "service", "app", "application", "system",
    "node", "container", "script", "command", "function", "class",
    "method", "module", "endpoint", "response", "request", "header",
    "payload", "log", "error", "user", "admin", "client", "agent",
    "tool", "pipeline", "build", "test", "deploy", "instance",
    "cluster", "volume", "network", "host", "domain", "certificate",
    "password", "secret", "connection", "session", "cache", "queue",
    "job", "task", "stream", "socket", "thread", "process", "proxy",
    "gateway", "router", "switch", "disk", "memory", "CPU", "GPU",
    "loop", "array", "list", "map", "object", "string", "integer",
    "boolean", "pointer", "handle", "fork", "branch", "commit", "PR",
    "issue", "ticket", "schema", "table", "row", "column", "index",
    "query", "migration", "hook", "event", "signal", "state", "stage",
    "phase", "step", "layer", "stack", "chain", "pattern", "template",
    "layout", "page", "screen", "view", "window", "panel", "menu",
    "form", "field", "button", "link",
    # Expanded - common tech nouns
    "data", "credential", "secret", "value", "setting",
    "parameter", "option", "flag", "attribute", "property",
    "infrastructure", "environment", "configuration", "deployment",
    "production", "development", "staging",
    "image", "binary", "package", "module",
    "release", "version", "update", "patch", "hotfix",
    "workload", "resource", "capacity",
    "traffic", "load",
    "latency", "throughput", "bandwidth", "worker", "schedule",
    "workflow", "orchestrator", "monitor", "alert",
    "metric", "dashboard", "report", "backup", "snapshot",
    "replica",
    "tenant", "organization", "workspace", "project", "repository",
    "registry", "artifact",
    "identifier", "name", "label", "tag", "namespace",
    "region", "zone", "location",
    "hostname", "socket", "protocol",
    "authority", "permission", "role", "policy", "rule", "ACL", "firewall",
    "hash", "salt", "cipher", "signature", "checksum",
    "mutation", "subscription", "topic",
    "document", "record", "entry",
    "blob", "directory", "path", "route",
    "code", "template", "manifest", "lock",
    "transaction", "lease",
    "platform", "framework", "library", "daemon", "runtime",
    "kernel", "driver", "firmware", "emulator", "simulator",
    "snapshot", "replica", "backup",
    "agent", "action", "trigger", "rule", "policy",
    "workflow", "orchestrator", "scheduler", "cron",
    "token", "session", "cookie", "payload", "header",
    "status", "health", "readiness", "liveness",
]

ACTION_VERBS = [
    # Core technical actions
    "set", "configure", "run", "start", "stop", "create", "delete",
    "update", "install", "deploy", "build", "test", "connect",
    "disconnect", "send", "receive", "read", "write", "open", "close",
    "save", "load", "export", "import", "generate", "parse", "compile",
    "execute", "authenticate", "authorize", "validate", "verify",
    "check", "monitor", "track", "log", "report", "calculate",
    "compute", "transform", "convert", "map", "filter", "sort",
    "merge", "split", "join", "search", "find", "register",
    "subscribe", "publish", "bind", "mount", "attach", "detach",
    "enable", "disable", "allow", "deny", "grant", "revoke",
    # Expanded - common doc actions
    "store", "provide", "include", "contain", "define", "specify",
    "control", "manage", "handle", "process", "display",
    "show", "return", "accept", "reject", "allow", "block",
    "require", "ensure", "maintain", "protect", "restrict",
    "audit", "rotate", "encrypt", "decrypt", "encode", "decode",
    "format", "structure", "organize", "resolve", "allocate",
    "assign", "release", "acquire", "fetch", "push", "pull",
    "watch", "listen", "forward", "route", "redirect",
    "copy", "move", "rename", "remove", "clear", "reset",
    "upgrade", "downgrade", "migrate", "sync",
    "optimize", "compress", "decompress", "archive", "extract",
    "initialize", "terminate", "suspend", "resume",
    "encrypt", "decrypt", "sign", "verify",
    "render", "compile", "transpile", "interpret",
    "mount", "unmount", "attach", "detach",
    "profile", "instrument", "benchmark", "measure",
    "document", "annotate", "comment",
    "encode", "decode", "serialize", "deserialize",
    "hash", "validate", "sanitize",
    "import", "export", "upload", "download", "sync",
    "install", "uninstall", "configure", "patch",
    "review", "approve", "reject", "merge",
    "implement", "integrate", "adopt",
    "refactor", "rewrite", "restructure",
]
